### ISSUE TITLE
Doesn't seem to work on v0.10.38

### ISSUE THREAD

**Issue by chan-dra** [d6u/web-playground#14]
I just tried this and running into exceptions.

```
Chandras-MacBook-Pro:example chandra$ npm install -g web-playground
npm WARN engine web-playground@0.4.0: wanted: {"node":">= 4"} (current: {"node":"0.10.38","npm":"2.7.3"})
npm WARN engine postcss@5.0.11: wanted: {"node":">=0.12"} (current: {"node":"0.10.38","npm":"2.7.3"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"2.7.3"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"2.7.3"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"2.7.3"})
 
> utf-8-validate@1.2.1 install /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
 
> bufferutil@1.2.1 install /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
 
> bufferutil@1.2.1 install /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"2.7.3"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"2.7.3"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.38","npm":"2.7.3"})
 
> utf-8-validate@1.2.1 install /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> spawn-sync@1.0.14 postinstall /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)
npm WARN package.json node-pre-gyp@0.6.15 No README data

> fsevents@1.0.5 install /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v11-darwin-x64/fse.node" is installed via remote

> node-sass@3.4.1 install /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/node-sass/vendor/darwin-x64-11/binding.node

> node-sass@3.4.1 postinstall /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/node-sass
> node scripts/build.js

Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync/error.log for more details
` /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/node_modules/node-sass/vendor/darwin-x64-11/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
/Users/chandra/.nvm/v0.10.38/bin/wpg -> /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/bin/wpg.js
web-playground@0.4.0 /Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground
├── normalize.css@3.0.3
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── portscanner@1.0.0 (async@0.1.15)
├── resolve@1.1.6
├── ejs@2.3.4
├── bluebird@2.10.2
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, on-finished@2.3.0, finalhandler@0.4.0, qs@4.0.0, debug@2.2.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.9, accepts@1.2.13)
├── postcss@5.0.11 (js-base64@2.1.9, supports-color@3.1.2, source-map@0.5.3)
├── ramda@0.17.1
├── js-yaml@3.4.3 (esprima@2.7.0, argparse@1.0.3)
├── autoprefixer@6.1.0 (num2fraction@1.2.2, postcss-value-parser@3.1.2, browserslist@1.0.1, caniuse-db@1.0.30000359)
├── rx@4.0.6
├── babel@5.8.29 (slash@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, output-file-sync@1.1.1, glob@5.0.15, source-map@0.5.3, lodash@3.10.1, babel-core@5.8.33)
├── browser-sync@2.9.12 (ucfirst@1.0.0, async-each-series@0.1.1, longest@1.0.1, emitter-steward@1.0.0, dev-ip@1.0.1, query-string@2.4.2, opn@3.0.3, browser-sync-client@2.3.4, serve-static@1.10.0, ua-parser-js@0.7.9, resp-modifier@5.0.2, connect@3.4.0, meow@3.3.0, immutable@3.7.5, foxy@11.1.3, anymatch@1.3.0, serve-index@1.7.2, easy-extender@2.3.1, eazy-logger@2.1.2, localtunnel@1.8.0, lodash@3.10.1, socket.io@1.3.7, browser-sync-ui@0.5.16)
├── chokidar@1.2.0 (arrify@1.0.0, path-is-absolute@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0, fsevents@1.0.5)
└── node-sass@3.4.1 (get-stdin@4.0.1, async-foreach@0.1.3, mkdirp@0.5.1, glob@5.0.15, npmconf@2.1.2, nan@2.1.0, meow@3.5.0, gaze@0.5.2, request@2.65.0, sass-graph@2.0.1, node-gyp@3.0.3, cross-spawn@2.0.0)
Chandras-MacBook-Pro:example chandra$ wpg 

/Users/chandra/.nvm/v0.10.38/lib/node_modules/web-playground/bin/wpg.js:5
const program = require('commander');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by chan-dra** [comment]
Nevermind, works only on Node V4, my bad. Closing.

**Comment by d6u** [comment]
Sorry, @chan-dra, I'd love to support Node 0.10, since that's I use at work everyday. But in order to implement simpler async flow controls, generators is a big plus, e.g. https://github.com/d6u/web-playground/blob/improve-logic-flow/lib/index.js#L9. Let me know if you encountered any other problems.
